-- ============================================================
-- 013_import_pipeline_mei.sql
-- Generated by import-pipeline-mei.js
-- Source: potensi closing mei.xlsx
-- Rows: 82
-- Generated: 2026-05-14T08:01:33.115Z
-- ============================================================

-- Remove existing pipeline data for these hunters
DELETE FROM konsumen
  WHERE status IN ('warm', 'hot', 'tidak_potensial')
  AND sales_hunter IN (
    'Aida (Rosmaida)',
    'Aldo (Rinaldo)',
    'Andre',
    'Frans',
    'Asun',
    'Ellen',
    'Firyal Badriyyah',
    'Lyndon Sumarli',
    'Prediman'
  );

-- [1] Iksak
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Aida (Rosmaida)' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Aida (Rosmaida)',
  'Lenni Natalia',
  'Iksak',
  'Central Hills',
  'CL',
  'hot',
  1110000000,
  NULL;

-- [2] Jocky
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Aida (Rosmaida)' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Aida (Rosmaida)',
  'M. Fiqri',
  'Jocky',
  'Central Hills',
  'PH 102',
  'hot',
  1347000000,
  NULL;

-- [3] Arik
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Aida (Rosmaida)' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Aida (Rosmaida)',
  'Vio Wahyuda',
  'Arik',
  'Central Hills',
  'SV 103',
  'hot',
  1187000000,
  NULL;

-- [4] Arifin
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Aida (Rosmaida)' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Aida (Rosmaida)',
  'M. Fiqri',
  'Arifin',
  'Central Hills',
  'SPH 15',
  'hot',
  1314000000,
  NULL;

-- [5] Bunga
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Aida (Rosmaida)' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Aida (Rosmaida)',
  'M. Fadjri Saputra',
  'Bunga',
  'Central Hills',
  'SV 111',
  'hot',
  1200000000,
  NULL;

-- [6] Arifin
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Aida (Rosmaida)' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Aida (Rosmaida)',
  'Lenni Natalia',
  'Arifin',
  'Central Hills',
  'SPH 96',
  'hot',
  1675000000,
  NULL;

-- [7] Ningsi
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Aida (Rosmaida)' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Aida (Rosmaida)',
  'M. Fiqri',
  'Ningsi',
  'Central Hills',
  'SH 76',
  'tidak_potensial',
  1530000000,
  NULL;

-- [8] Sani
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Aida (Rosmaida)' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Aida (Rosmaida)',
  'M. Fiqri',
  'Sani',
  'Central Hills',
  'PH',
  'tidak_potensial',
  NULL,
  NULL;

-- [9] Nisa
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Aldo (Rinaldo)' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Aldo (Rinaldo)',
  'Yossi Eka Nofrita',
  'Nisa',
  'Central Hills',
  'SV 85',
  'hot',
  2152800000,
  'Menunggu orang tua ke lokasi unit';

-- [10] Dedi
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Aldo (Rinaldo)' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Aldo (Rinaldo)',
  'Abel Shevcenko',
  'Dedi',
  'Central Hills',
  'SV 116',
  'hot',
  1080000000,
  'Tgl 15 visit ke-2 untuk beri keputusan';

-- [11] Hasbullah
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Andre' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Andre',
  'Salsabila Rahman',
  'Hasbullah',
  'Central Tiban',
  'CT-66',
  'hot',
  1260000000,
  'Ada kendala visit ulang; tinggal lunasi BF & ttd SKUP';

-- [12] Indah
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Andre' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Andre',
  'Riezkya Adella',
  'Indah',
  'Central Raya Tiban',
  'CRT A-16',
  'warm',
  1177200000,
  'Menunggu pencairan rumah yang dijual';

-- [13] Dedi Hidayat
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Andre' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Andre',
  'Ari Kurnia Sandy',
  'Dedi Hidayat',
  'Central Tiban',
  'CT-65',
  'hot',
  860000000,
  'Rencana cash keras 1–6 kali; hitung dana project masuk';

-- [14] Trisna
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Andre' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Andre',
  'Dea Alvony Agista',
  'Trisna',
  'Central Tiban',
  'CT-70',
  'warm',
  1260000000,
  'Masih membandingkan dengan proyek lain; masih di-follow up';

-- [15] Vanesha
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Andre' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Andre',
  'Dea Alvony Agista',
  'Vanesha',
  'Central Tiban',
  'CT-137',
  'tidak_potensial',
  1177200000,
  'Mencari rumah ready';

-- [16] Yanti
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Andre' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Andre',
  'Dea Alvony Agista',
  'Yanti',
  'Central Tiban',
  'CT-15',
  'warm',
  1040400000,
  'Menunggu keputusan suami (pelaut)';

-- [17] Reni
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Andre' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Andre',
  'Dea Alvony Agista',
  'Reni',
  'Central Tiban',
  'CT-20',
  'tidak_potensial',
  1040400000,
  'Tidak masuk budget';

-- [18] Elsa
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Andre' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Andre',
  'Ari Kurnia Sandy',
  'Elsa',
  'Central Tiban',
  'CT-137',
  'warm',
  1040400000,
  'Menunggu visit pasangan dari Singapura';

-- [19] Tuti
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Andre' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Andre',
  'Ari Kurnia Sandy',
  'Tuti',
  'Central Tiban',
  'CT-36',
  'warm',
  1040400000,
  'Menunggu visit pasangan dari Singapura';

-- [20] Intan
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Andre' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Andre',
  'Ari Kurnia Sandy',
  'Intan',
  'Central Tiban',
  'CT-35',
  'tidak_potensial',
  1040400000,
  'Cicilan mobil masih 3 tahun; ragu KPR';

-- [21] May
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Andre' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Andre',
  'Riezkya Adella',
  'May',
  'Central Tiban',
  'CT-137',
  'tidak_potensial',
  934200000,
  'Tidak masuk budget; mau cash bertahap 6 jt/bulan';

-- [22] Ningsih
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Andre' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Andre',
  'Riezkya Adella',
  'Ningsih',
  'Central Tiban',
  'CT-137',
  'tidak_potensial',
  934200000,
  'Visit lokasi sendiri; tidak masuk budget';

-- [23] Galih
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Andre' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Andre',
  'Syarah Mustika',
  'Galih',
  'Central Tiban',
  'CT Type 72',
  'tidak_potensial',
  1040400000,
  'Tidak masuk budget';

-- [24] Diah
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Andre' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Andre',
  'Syarah Mustika',
  'Diah',
  'Central Tiban',
  'CT-137',
  'tidak_potensial',
  934200000,
  'Cari 1 lantai';

-- [25] Rika
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Andre' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Andre',
  'Syarah Mustika',
  'Rika',
  'Central Tiban',
  'CT Type 72',
  'tidak_potensial',
  1040400000,
  'Hanya lihat-lihat';

-- [26] Adhelia
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Andre' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Andre',
  'Syarah Mustika',
  'Adhelia',
  'Central Tiban',
  'CT Type 72',
  'tidak_potensial',
  1040400000,
  'Lihat-lihat; beli niatnya tahun depan';

-- [27] Michelle
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Andre' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Andre',
  'Syarah Mustika',
  'Michelle',
  'Central Tiban',
  'CT Type 72',
  'tidak_potensial',
  1040400000,
  'WNA; minimum beli rumah di Batam Rp 2 M';

-- [28] Handoko
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Andre' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Andre',
  'Syarah Mustika',
  'Handoko',
  'Central Tiban',
  'CT Type 72',
  'warm',
  1040400000,
  'Masih membandingkan dengan proyek lain';

-- [29] Juli
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Andre' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Andre',
  'Syarah Mustika',
  'Juli',
  'Central Tiban',
  'CT Type 72',
  'warm',
  1040400000,
  'Tertarik; menunggu rumahnya terjual dulu';

-- [30] Andrew
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Andre' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Andre',
  'Syarah Mustika',
  'Andrew',
  'Central Tiban',
  'CT-137',
  'tidak_potensial',
  934200000,
  'Menunggu istri lahiran dulu';

-- [31] Edi
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Andre' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Andre',
  'Salsabila Rahman',
  'Edi',
  'Central Tiban',
  'CT-137',
  'tidak_potensial',
  934200000,
  'Tidak masuk budget';

-- [32] Haikal
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Andre' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Andre',
  'Salsabila Rahman',
  'Haikal',
  'Central Tiban',
  'CT-137',
  'tidak_potensial',
  934200000,
  'Keluarga kurang setuju';

-- [33] Veni
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Andre' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Andre',
  'Salsabila Rahman',
  'Veni',
  'Central Tiban',
  'CT-137',
  'tidak_potensial',
  934200000,
  'Ragu dekat laut & bakau; diskusi dulu dengan suami';

-- [34] Mela
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Andre' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Andre',
  'Salsabila Rahman',
  'Mela',
  'Central Tiban',
  'CT-137',
  'tidak_potensial',
  934200000,
  'Tidak masuk budget; takut floating; maks cicilan 5 jt';

-- [35] Rika
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Frans' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Frans',
  'Shinta Okvianti',
  'Rika',
  'Central Tiban',
  'CT 70',
  'warm',
  1156000000,
  'Masih pertimbangan dengan keluarga';

-- [36] Andri
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Frans' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Frans',
  'M. Amirullah',
  'Andri',
  'Central Raya Tiban',
  'CT 70',
  'warm',
  1156000000,
  'Masih diskusi dengan istri terkait angsuran KPR';

-- [37] Ce Yani
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Frans' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Frans',
  'M. Amirullah',
  'Ce Yani',
  'Central Tiban',
  'CT 68',
  'tidak_potensial',
  1156000000,
  'Tidak suka dengan posisi dapur';

-- [38] Kayel
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Frans' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Frans',
  'Nisa Nur fadhila',
  'Kayel',
  'Central Tiban',
  'CT 68',
  'warm',
  1156000000,
  'Konsumen masih di luar negeri';

-- [39] Medya
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Asun' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Asun',
  'Sentia Julika',
  'Medya',
  'Central Laguna Hills',
  'A9 No.17',
  'hot',
  597645000,
  NULL;

-- [40] Zidan
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Asun' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Asun',
  'Sentia Julika',
  'Zidan',
  'Central Laguna Hills',
  'A9 No.18',
  'hot',
  597645000,
  NULL;

-- [41] Miftha
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Asun' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Asun',
  'Sentia Julika',
  'Miftha',
  'Central Laguna Hills',
  'D2 No.10',
  'hot',
  632700000,
  NULL;

-- [42] Alson
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Asun' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Asun',
  'Santoso',
  'Alson',
  'Central Raya Batu Aji',
  'F No.1',
  'tidak_potensial',
  NULL,
  NULL;

-- [43] Meliana
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Asun' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Asun',
  'Santoso',
  'Meliana',
  'Central Laguna Hills',
  '—',
  'hot',
  597645000,
  NULL;

-- [44] Santos
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Asun' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Asun',
  'Nurlela',
  'Santos',
  'Central Raya Batu Aji',
  'G No.1',
  'tidak_potensial',
  NULL,
  NULL;

-- [45] Erick
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Asun' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Asun',
  'Nurlela',
  'Erick',
  'Central Laguna Hills',
  '—',
  'hot',
  597645000,
  NULL;

-- [46] Desy Cristina
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Ellen' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Ellen',
  'Ferdinan Bangun',
  'Desy Cristina',
  NULL,
  '—',
  'tidak_potensial',
  410000000,
  NULL;

-- [47] Kimchang Sun
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Ellen' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Ellen',
  'Ferdinan Bangun',
  'Kimchang Sun',
  'Central Laguna Hills',
  '45',
  'hot',
  629100000,
  NULL;

-- [48] Nopia Sari
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Ellen' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Ellen',
  'Ferdinan Bangun',
  'Nopia Sari',
  'Central Raya Tanjung Uncang',
  '32',
  'hot',
  299000000,
  NULL;

-- [49] Dayu Lubis
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Ellen' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Ellen',
  'Ferdinan Bangun',
  'Dayu Lubis',
  'Central Laguna Hills',
  '45',
  'tidak_potensial',
  629100000,
  NULL;

-- [50] Eka Yudhi Syahputra
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Ellen' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Ellen',
  'Febry Nairi',
  'Eka Yudhi Syahputra',
  'Central Raya Batu Aji',
  '30/82',
  'tidak_potensial',
  410000000,
  NULL;

-- [51] Ardiamsyah Buton
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Ellen' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Ellen',
  'Febry Nairi',
  'Ardiamsyah Buton',
  'Central Raya Tanjung Uncang',
  '32',
  'hot',
  299000000,
  NULL;

-- [52] Teti
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Ellen' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Ellen',
  'Febry Nairi',
  'Teti',
  'Central Raya Batu Aji',
  '30/82',
  'tidak_potensial',
  410000000,
  NULL;

-- [53] Muhammad Rasit Harahap
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Ellen' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Ellen',
  'Febry Nairi',
  'Muhammad Rasit Harahap',
  'Central Raya Batu Aji',
  '80',
  'tidak_potensial',
  739000000,
  NULL;

-- [54] Mechele
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Ellen' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Ellen',
  'Febry Nairi',
  'Mechele',
  'Central Raya Batu Aji',
  '80',
  'hot',
  739000000,
  NULL;

-- [55] Siti
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Ellen' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Ellen',
  'Rio Pratama',
  'Siti',
  'Central Raya Tanjung Uncang',
  '32',
  'tidak_potensial',
  299000000,
  NULL;

-- [56] Zia
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Ellen' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Ellen',
  'Rio Pratama',
  'Zia',
  'Central Raya Tanjung Uncang',
  '32',
  'hot',
  299000000,
  NULL;

-- [57] Ermi
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Ellen' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Ellen',
  'Rio Pratama',
  'Ermi',
  'Central Raya Tanjung Uncang',
  '32',
  'tidak_potensial',
  299000000,
  NULL;

-- [58] Rahmat
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Ellen' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Ellen',
  'Tri Andy Kurniawan',
  'Rahmat',
  'Central Laguna Hills',
  '45',
  'hot',
  629100000,
  NULL;

-- [59] Sri Devi
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Ellen' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Ellen',
  'Eka Vitria Lestari',
  'Sri Devi',
  'Central Laguna Hills',
  '45',
  'hot',
  629100000,
  NULL;

-- [60] Raka
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Firyal Badriyyah' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Firyal Badriyyah',
  'Adi Chandra',
  'Raka',
  'SCC - Valleyside',
  'Cedar No. 65',
  'hot',
  1132000000,
  NULL;

-- [61] Dr. Victor
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Firyal Badriyyah' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Firyal Badriyyah',
  'Adi Chandra',
  'Dr. Victor',
  'SCC - Hillside',
  'Kavling RW No. 61',
  'hot',
  2127500000,
  NULL;

-- [62] Dr. Adi
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Firyal Badriyyah' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Firyal Badriyyah',
  'Adi Chandra',
  'Dr. Adi',
  'SCC - Hillside',
  'RW No. 15',
  'hot',
  1752800000,
  NULL;

-- [63] Dr. Nazarrudin
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Firyal Badriyyah' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Firyal Badriyyah',
  'Adi Chandra',
  'Dr. Nazarrudin',
  'SCC - Hillside',
  'Kavling',
  'hot',
  1000000000,
  NULL;

-- [64] Pak Haryanto
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Firyal Badriyyah' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Firyal Badriyyah',
  'Adi Chandra',
  'Pak Haryanto',
  'SCC - Hillside',
  'Kavling',
  'hot',
  1000000000,
  NULL;

-- [65] Mr. Derrick
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Firyal Badriyyah' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Firyal Badriyyah',
  'Agent Liston',
  'Mr. Derrick',
  'SCC - Hillside',
  'Villa Serenity No. 7',
  'hot',
  3788000000,
  NULL;

-- [66] Leni
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Lyndon Sumarli' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Lyndon Sumarli',
  'Kiki',
  'Leni',
  'Central Hills',
  'AH 30',
  'hot',
  988000000,
  NULL;

-- [67] Irvan Halolo
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Lyndon Sumarli' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Lyndon Sumarli',
  'Riduan Hasudungan Hutabarat',
  'Irvan Halolo',
  'Central Hills',
  'AH 79',
  'hot',
  1384000000,
  NULL;

-- [68] —
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Lyndon Sumarli' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Lyndon Sumarli',
  'CS Property Agent',
  '—',
  'Central Hills',
  'SPH 30',
  'hot',
  1000000000,
  NULL;

-- [69] —
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Lyndon Sumarli' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Lyndon Sumarli',
  'GPM Property',
  '—',
  'Central Hills',
  'SV 8',
  'tidak_potensial',
  1191600000,
  'Tidak ada kabar';

-- [70] —
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Lyndon Sumarli' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Lyndon Sumarli',
  'AMP Property',
  '—',
  'Central Raya Tanjung Uncang',
  '—',
  'tidak_potensial',
  NULL,
  'Unit tidak ada';

-- [71] —
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Lyndon Sumarli' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Lyndon Sumarli',
  'CS Property',
  '—',
  'Central Tiban',
  'CT 60',
  'tidak_potensial',
  1368000000,
  'Konsumen mundur';

-- [72] Sudianto
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Lyndon Sumarli' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Lyndon Sumarli',
  'Mhd Sidiq Abdussalam',
  'Sudianto',
  'Central Hills',
  '—',
  'tidak_potensial',
  NULL,
  'Tidak cocok fasad di Central Hills';

-- [73] Agato
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Lyndon Sumarli' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Lyndon Sumarli',
  'Propnex Property',
  'Agato',
  'Central Hills',
  'SV',
  'tidak_potensial',
  NULL,
  'Tidak bisa dihubungi lagi';

-- [74] Agra
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Prediman' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Prediman',
  'Fani',
  'Agra',
  'Central Raya Tanjung Uncang',
  'Type 32',
  'hot',
  292200000,
  'Menunggu SLIK keluar';

-- [75] Lukman
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Prediman' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Prediman',
  'Fani',
  'Lukman',
  'Central Raya Tanjung Uncang',
  'Type 32',
  'warm',
  292200000,
  'Berunding dengan istri';

-- [76] Dela
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Prediman' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Prediman',
  'Gallih Dwi Gumelar',
  'Dela',
  'Central Raya Tanjung Uncang',
  'Type 32',
  'hot',
  315000000,
  'Menunggu SLIK & konfirmasi jadwal kantor hari libur';

-- [77] Susanto Siregar
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Prediman' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Prediman',
  'Crisna Ardhianysah',
  'Susanto Siregar',
  'Central Raya Tanjung Uncang',
  'Ruko (2 unit)',
  'hot',
  1123200000,
  'Besok keputusan';

-- [78] Nizam
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Prediman' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Prediman',
  'Crisna Ardhianysah',
  'Nizam',
  'Central Raya Tanjung Uncang',
  'Type 32',
  'hot',
  315000000,
  'Tertarik diskon 10+10; selisih angsuran jauh vs diskon 10%';

-- [79] Bu Naura
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Prediman' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Prediman',
  'Muhammad Rafie',
  'Bu Naura',
  'Central Raya Tanjung Uncang',
  'Type 32',
  'warm',
  315000000,
  'Menunggu KTP; cek SLIK';

-- [80] Pakde Yoga
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Prediman' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Prediman',
  'Muhammad Rafie',
  'Pakde Yoga',
  'Central Raya Tanjung Uncang',
  'Type 32',
  'warm',
  315000000,
  'KPR – konfirmasi surat kerja permanen anak';

-- [81] Fauzan
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Prediman' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Prediman',
  'Gallih Dwi Gumelar',
  'Fauzan',
  'Central Raya Tanjung Uncang',
  'Type 36',
  'warm',
  NULL,
  'Reschedule visit ke hari libur minggu depan';

-- [82] Lia
INSERT INTO konsumen (user_id, sales_hunter, sales_person, name, project, unit, status, nilai_hjr, notes)
SELECT
  COALESCE(
    (SELECT id FROM users WHERE name = 'Prediman' LIMIT 1),
    (SELECT id FROM users WHERE role = 'admin' LIMIT 1)
  ),
  'Prediman',
  'Gallih Dwi Gumelar',
  'Lia',
  'Central Raya Tanjung Uncang',
  'Type 32',
  'hot',
  315000000,
  'Sudah visit; malam ini berunding suami; follow up besok';
